### ISSUE TITLE
Missing java symlinks after migration from CentOS 8

### ISSUE THREAD

**Issue by leifhetle** [AlmaLinux/almalinux-deploy#50]
It seems symlinks created when installing java in /etc/alternatives gets deleted when migrating Centos 8 to Almalinux

Before migration
[root@centos8 ~]# ll /etc/alternatives/
total 0
lrwxrwxrwx. 1 root root 77 april 22 21:08 alt-java -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/alt-java
lrwxrwxrwx. 1 root root 81 april 22 21:08 alt-java.1.gz -> /usr/share/man/man1/alt-java-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 39 april  2 10:01 cifs-idmap-plugin -> /usr/lib64/cifs-utils/cifs_idmap_sss.so
lrwxrwxrwx. 1 root root 22 april  2 10:01 ifdown -> /usr/libexec/nm-ifdown
lrwxrwxrwx. 1 root root 20 april  2 10:01 ifup -> /usr/libexec/nm-ifup
lrwxrwxrwx. 1 root root 73 april 22 21:08 java -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/java
lrwxrwxrwx. 1 root root 77 april 22 21:08 java.1.gz -> /usr/share/man/man1/java-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 72 april 22 21:08 jjs -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/jjs
lrwxrwxrwx. 1 root root 76 april 22 21:08 jjs.1.gz -> /usr/share/man/man1/jjs-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 64 april 22 21:08 jre -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre
lrwxrwxrwx. 1 root root 64 april 22 21:08 jre_1.8.0 -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre
lrwxrwxrwx. 1 root root 59 april 22 21:08 jre_1.8.0_openjdk -> /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64
lrwxrwxrwx. 1 root root 64 april 22 21:08 jre_openjdk -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre
lrwxrwxrwx. 1 root root 76 april 22 21:08 keytool -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/keytool
lrwxrwxrwx. 1 root root 80 april 22 21:08 keytool.1.gz -> /usr/share/man/man1/keytool-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 15 april  2 10:13 ld -> /usr/bin/ld.bfd
lrwxrwxrwx. 1 root root 34 april  2 10:01 libnssckbi.so.x86_64 -> /usr/lib64/pkcs11/p11-kit-trust.so
lrwxrwxrwx. 1 root root 45 april  2 10:13 libwbclient.so.0.15-64 -> /usr/lib64/samba/wbclient/libwbclient.so.0.15
lrwxrwxrwx. 1 root root 29 april  2 10:13 ncman -> /usr/share/man/man1/ncat.1.gz
lrwxrwxrwx. 1 root root 13 april  2 10:13 nmap -> /usr/bin/ncat
lrwxrwxrwx. 1 root root 73 april 22 21:08 orbd -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/orbd
lrwxrwxrwx. 1 root root 77 april 22 21:08 orbd.1.gz -> /usr/share/man/man1/orbd-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 76 april 22 21:08 pack200 -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/pack200
lrwxrwxrwx. 1 root root 80 april 22 21:08 pack200.1.gz -> /usr/share/man/man1/pack200-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 79 april 22 21:08 policytool -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/policytool
lrwxrwxrwx. 1 root root 83 april 22 21:08 policytool.1.gz -> /usr/share/man/man1/policytool-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 22 april  2 10:01 python -> /usr/libexec/no-python
lrwxrwxrwx. 1 root root 73 april 22 21:08 rmid -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/rmid
lrwxrwxrwx. 1 root root 77 april 22 21:08 rmid.1.gz -> /usr/share/man/man1/rmid-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 80 april 22 21:08 rmiregistry -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/rmiregistry
lrwxrwxrwx. 1 root root 84 april 22 21:08 rmiregistry.1.gz -> /usr/share/man/man1/rmiregistry-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 79 april 22 21:08 servertool -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/servertool
lrwxrwxrwx. 1 root root 83 april 22 21:08 servertool.1.gz -> /usr/share/man/man1/servertool-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 78 april 22 21:08 tnameserv -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/tnameserv
lrwxrwxrwx. 1 root root 82 april 22 21:08 tnameserv.1.gz -> /usr/share/man/man1/tnameserv-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 78 april 22 21:08 unpack200 -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64/jre/bin/unpack200
lrwxrwxrwx. 1 root root 82 april 22 21:08 unpack200.1.gz -> /usr/share/man/man1/unpack200-java-1.8.0-openjdk-1.8.0.282.b08-2.el8_3.x86_64.1.gz
lrwxrwxrwx. 1 root root 43 april  2 10:01 unversioned-python-man -> /usr/share/man/man1/unversioned-python.1.gz

After migration:
[root@centos8 ~]# ll /etc/alternatives/
lrwxrwxrwx. 1 root root 39 april  2 10:01 cifs-idmap-plugin -> /usr/lib64/cifs-utils/cifs_idmap_sss.so
lrwxrwxrwx. 1 root root 22 april  2 10:01 ifdown -> /usr/libexec/nm-ifdown
lrwxrwxrwx. 1 root root 20 april  2 10:01 ifup -> /usr/libexec/nm-ifup
lrwxrwxrwx. 1 root root 15 april  2 10:13 ld -> /usr/bin/ld.bfd
lrwxrwxrwx. 1 root root 34 april  2 10:01 libnssckbi.so.x86_64 -> /usr/lib64/pkcs11/p11-kit-trust.so
lrwxrwxrwx. 1 root root 45 april  2 10:13 libwbclient.so.0.15-64 -> /usr/lib64/samba/wbclient/libwbclient.so.0.15
lrwxrwxrwx. 1 root root 29 april  2 10:13 ncman -> /usr/share/man/man1/ncat.1.gz
lrwxrwxrwx. 1 root root 13 april  2 10:13 nmap -> /usr/bin/ncat
lrwxrwxrwx. 1 root root 22 april  2 10:01 python -> /usr/libexec/no-python
lrwxrwxrwx. 1 root root 43 april  2 10:01 unversioned-python-man -> /usr/share/man/man1/unversioned-python.1.gz
 
Added a logfile how to reproduce.

[logfile.txt](https://github.com/AlmaLinux/almalinux-deploy/files/6360782/logfile.txt)

**Comment by titan-dn** [comment]
I've tested 3 cases:
- CentOS8 -> Alma8
- Oracle8 -> Alma8
- RHEL8 -> Alma8
all of them migrated fine and symbol links presented

**Comment by leifhetle** [comment]
It happened on 2 production systems I migrated and in my lab.
It was not a really big thing, just dnf erase java-1.8.0-openjdk-headless and install afterwards and everything ok.

It happened on 3 systems.
Would be interested in knowing what I did wrong though. Find it strange this issue only occurs when I am involved...

**Comment by peteeckel** [comment]
Same here, on all three systems I run Java on. CentOS 8->Alma 8, alternatives were missing.

**Comment by mercma** [comment]
I'm experiencing the same issue when migrating from CentOS8 -> Alma.  I have ipa installed on the host I am attempting to upgrade, the ipa upgrade fails due to tomcat not restarted because it can no longer find the java install.

From /var/log/ipaupgrade.log

> 2021-05-01T18:00:01Z DEBUG stderr=/usr/sbin/tomcat: JAVA_HOME is not set and default java installation was not found. JAVA_HOME for system applications can be set in java.conf in /etc/java

I have also noticed that the versions of tomcatjss installed are different

> CentOS - tomcatjss-7.5.0-1_module_el8.3.0+470+ca766673.noarch
> Alma - tomcatjss-7.5.0-1.module_el8.3.0+2061+d5cd4219.noarch

I ran a 'dnf update -y' on the CentOS system before attempting the install.

> [root@ipa2 ~]# dnf update
Last metadata expiration check: 0:28:09 ago on Sat 01 May 2021 02:31:11 PM EDT.
Dependencies resolved.
Nothing to do.
Complete!

I can attempt the upgrade again (I snapshot before the upgrade) to provide the differences from an 'alternatives --list' if that would be helpful?

**Comment by bdpz** [comment]
Same problem here, with same up2date Centos 8 and latest almalinux-deploy.sh script

I confirm that dnf erase java-11-openjdk-headless + dnf install java-11-openjdk-headless solve the problem with alternatives, but I have done that because I could.

**Comment by mercma** [comment]
I fixed my issue above by doing the following:

1. Run the migration script, don't reboot
2. rpm -e --nodeps java-1.8.0-openjdk-devel-1.8.0.292.b10-0.el8_3.x86_64 java-1.8.0-openjdk-headless-1.8.0.292.b10-0.el8_3.x86_64 java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
3. dnf install java-1.8.0-openjdk-devel-1.8.0.292.b10-0.el8_3.x86_64 java-1.8.0-openjdk-headless-1.8.0.292.b10-0.el8_3.x86_64 java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
4. edit /etc/resolv.conf, add the other ipa server - NOTE: I have the DNS server local to the IPA install
5. run the ipa-server-upgrade script manually
6. reboot

**Comment by andrewlukoshko** [comment]
Hello everyone.
We're already testing a solution and will merge it soon: https://github.com/AlmaLinux/almalinux-deploy/pull/49/commits/5d9cbaa5bc612b96dd87e20283cb4542528cd6df

**Comment by andrewlukoshko** [comment]
Fixed by https://github.com/AlmaLinux/almalinux-deploy/commit/17e1ca5ad2d7f5bc9525901bbcf4e215279e4d19
Closing.

**Comment by bdpz** [comment]
I have done a test, and the problem is still here (with other).

update-alternatives may show (null). Example :
...
 slave rmiregistry.1.gz: /usr/share/man/man1/rmiregistry-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
 slave servertool.1.gz: (null)
 slave tnameserv.1.gz: (null)
...


And in the tmp file used :

more /tmp/java_backup.EHCakQ 
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/alt-java alt-java
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jjs jjs
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/keytool keytool
(null) orbd
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/pack200 pack200
(null) policytool
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/rmid rmid
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/rmiregistry rmiregistry
(null) servertool
(null) tnameserv
...

The result is some bad links :

lrwxrwxrwx  1 root root 79 May 17 15:04 rmiregistry.1.gz -> /usr/share/man/man1/rmiregistry-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root  6 May 17 15:04 servertool -> '(null)'
lrwxrwxrwx  1 root root  6 May 17 15:04 servertool.1.gz -> '(null)'

But the main problem is that java is still not here :

ll /etc/alternatives
total 0
lrwxrwxrwx  1 root root 68 May 17 15:04 alt-java -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/alt-java
lrwxrwxrwx  1 root root 76 May 17 15:04 alt-java.1.gz -> /usr/share/man/man1/alt-java-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 39 Jun 16  2020 cifs-idmap-plugin -> /usr/lib64/cifs-utils/cifs_idmap_sss.so
lrwxrwxrwx  1 root root 25 Mar  9  2020 easy_install-3 -> /usr/bin/easy_install-3.6
lrwxrwxrwx  1 root root 22 Sep 21  2020 ifdown -> /usr/libexec/nm-ifdown
lrwxrwxrwx  1 root root 20 Sep 21  2020 ifup -> /usr/libexec/nm-ifup
lrwxrwxrwx  1 root root 72 May 17 15:04 java.1.gz -> /usr/share/man/man1/java-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 63 May 17 15:04 jjs -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jjs
lrwxrwxrwx  1 root root 71 May 17 15:04 jjs.1.gz -> /usr/share/man/man1/jjs-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 55 May 17 15:04 jre -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
...

I will try to modify the script.

This is the original /etc/alternatives before the script :

ll /etc/alternatives/
total 0
lrwxrwxrwx  1 root root 68 May  2 17:58 alt-java -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/alt-java
lrwxrwxrwx  1 root root 76 May  2 17:58 alt-java.1.gz -> /usr/share/man/man1/alt-java-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 39 Jun 16  2020 cifs-idmap-plugin -> /usr/lib64/cifs-utils/cifs_idmap_sss.so
lrwxrwxrwx  1 root root 25 Mar  9  2020 easy_install-3 -> /usr/bin/easy_install-3.6
lrwxrwxrwx  1 root root 22 Sep 21  2020 ifdown -> /usr/libexec/nm-ifdown
lrwxrwxrwx  1 root root 20 Sep 21  2020 ifup -> /usr/libexec/nm-ifup
lrwxrwxrwx  1 root root 65 May  2 17:58 jaotc -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jaotc
lrwxrwxrwx  1 root root 63 May  2 17:58 jar -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jar
lrwxrwxrwx  1 root root 71 May  2 17:58 jar.1.gz -> /usr/share/man/man1/jar-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 69 May  2 17:58 jarsigner -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jarsigner
lrwxrwxrwx  1 root root 77 May  2 17:58 jarsigner.1.gz -> /usr/share/man/man1/jarsigner-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 64 May  2 17:58 java -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/java
lrwxrwxrwx  1 root root 72 May  2 17:58 java.1.gz -> /usr/share/man/man1/java-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 65 May  2 17:58 javac -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/javac
lrwxrwxrwx  1 root root 73 May  2 17:58 javac.1.gz -> /usr/share/man/man1/javac-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 67 May  2 17:58 javadoc -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/javadoc
lrwxrwxrwx  1 root root 75 May  2 17:58 javadoc.1.gz -> /usr/share/man/man1/javadoc-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 65 May  2 17:58 javap -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/javap
lrwxrwxrwx  1 root root 73 May  2 17:58 javap.1.gz -> /usr/share/man/man1/javap-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 55 May  2 17:58 java_sdk -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 55 May  2 17:58 java_sdk_11 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 55 May  2 17:58 java_sdk_11_openjdk -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 55 May  2 17:58 java_sdk_openjdk -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 64 May  2 17:58 jcmd -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jcmd
lrwxrwxrwx  1 root root 72 May  2 17:58 jcmd.1.gz -> /usr/share/man/man1/jcmd-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 68 May  2 17:58 jconsole -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jconsole
lrwxrwxrwx  1 root root 76 May  2 17:58 jconsole.1.gz -> /usr/share/man/man1/jconsole-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 63 May  2 17:58 jdb -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jdb
lrwxrwxrwx  1 root root 71 May  2 17:58 jdb.1.gz -> /usr/share/man/man1/jdb-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 69 May  2 17:58 jdeprscan -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jdeprscan
lrwxrwxrwx  1 root root 65 May  2 17:58 jdeps -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jdeps
lrwxrwxrwx  1 root root 73 May  2 17:58 jdeps.1.gz -> /usr/share/man/man1/jdeps-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 63 May  2 17:58 jfr -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jfr
lrwxrwxrwx  1 root root 65 May  2 17:58 jhsdb -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jhsdb
lrwxrwxrwx  1 root root 66 May  2 17:58 jimage -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jimage
lrwxrwxrwx  1 root root 65 May  2 17:58 jinfo -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jinfo
lrwxrwxrwx  1 root root 73 May  2 17:58 jinfo.1.gz -> /usr/share/man/man1/jinfo-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 63 May  2 17:58 jjs -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jjs
lrwxrwxrwx  1 root root 71 May  2 17:58 jjs.1.gz -> /usr/share/man/man1/jjs-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 65 May  2 17:58 jlink -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jlink
lrwxrwxrwx  1 root root 64 May  2 17:58 jmap -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jmap
lrwxrwxrwx  1 root root 72 May  2 17:58 jmap.1.gz -> /usr/share/man/man1/jmap-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 64 May  2 17:58 jmod -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jmod
lrwxrwxrwx  1 root root 63 May  2 17:58 jps -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jps
lrwxrwxrwx  1 root root 71 May  2 17:58 jps.1.gz -> /usr/share/man/man1/jps-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 55 May  2 17:58 jre -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 55 May  2 17:58 jre_11 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 54 May  2 17:58 jre_11_openjdk -> /usr/lib/jvm/jre-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
lrwxrwxrwx  1 root root 64 May  2 17:58 jre_1.8.0 -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64/jre
lrwxrwxrwx  1 root root 59 May  2 17:58 jre_1.8.0_openjdk -> /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
lrwxrwxrwx  1 root root 64 May  2 17:58 jre_openjdk -> /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64/jre
lrwxrwxrwx  1 root root 70 May  2 17:58 jrunscript -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jrunscript
lrwxrwxrwx  1 root root 78 May  2 17:58 jrunscript.1.gz -> /usr/share/man/man1/jrunscript-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 66 May  2 17:58 jshell -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jshell
lrwxrwxrwx  1 root root 66 May  2 17:58 jstack -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jstack
lrwxrwxrwx  1 root root 74 May  2 17:58 jstack.1.gz -> /usr/share/man/man1/jstack-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 65 May  2 17:58 jstat -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jstat
lrwxrwxrwx  1 root root 73 May  2 17:58 jstat.1.gz -> /usr/share/man/man1/jstat-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 66 May  2 17:58 jstatd -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/jstatd
lrwxrwxrwx  1 root root 74 May  2 17:58 jstatd.1.gz -> /usr/share/man/man1/jstatd-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 67 May  2 17:58 keytool -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/keytool
lrwxrwxrwx  1 root root 75 May  2 17:58 keytool.1.gz -> /usr/share/man/man1/keytool-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 15 Jun 16  2020 ld -> /usr/bin/ld.bfd
lrwxrwxrwx. 1 root root 34 Mar  9  2020 libnssckbi.so.x86_64 -> /usr/lib64/pkcs11/p11-kit-trust.so
lrwxrwxrwx  1 root root 23 Aug 23  2020 llvm-config -> /usr/bin/llvm-config-64
lrwxrwxrwx  1 root root 26 Jun 16  2020 mta -> /usr/sbin/sendmail.postfix
lrwxrwxrwx  1 root root 40 Jun 16  2020 mta-aliasesman -> /usr/share/man/man5/aliases.postfix.5.gz
lrwxrwxrwx  1 root root 22 Jun 16  2020 mta-mailq -> /usr/bin/mailq.postfix
lrwxrwxrwx  1 root root 38 Jun 16  2020 mta-mailqman -> /usr/share/man/man1/mailq.postfix.1.gz
lrwxrwxrwx  1 root root 27 Jun 16  2020 mta-newaliases -> /usr/bin/newaliases.postfix
lrwxrwxrwx  1 root root 43 Jun 16  2020 mta-newaliasesman -> /usr/share/man/man1/newaliases.postfix.1.gz
lrwxrwxrwx  1 root root 23 Jun 16  2020 mta-pam -> /etc/pam.d/smtp.postfix
lrwxrwxrwx  1 root root 22 Jun 16  2020 mta-rmail -> /usr/bin/rmail.postfix
lrwxrwxrwx  1 root root 25 Jun 16  2020 mta-sendmail -> /usr/lib/sendmail.postfix
lrwxrwxrwx  1 root root 41 Jun 16  2020 mta-sendmailman -> /usr/share/man/man1/sendmail.postfix.1.gz
lrwxrwxrwx  1 root root 38 Jun 16  2020 mta-smtpdman -> /usr/share/man/man8/smtpd.postfix.8.gz
lrwxrwxrwx  1 root root 29 Mar  9  2020 ncman -> /usr/share/man/man1/ncat.1.gz
lrwxrwxrwx  1 root root 13 Mar  9  2020 nmap -> /usr/bin/ncat
lrwxrwxrwx  1 root root 67 May  2 17:58 pack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/pack200
lrwxrwxrwx  1 root root 75 May  2 17:58 pack200.1.gz -> /usr/share/man/man1/pack200-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 27 Nov 13  2020 pgsql-clusterdb -> /usr/pgsql-12/bin/clusterdb
lrwxrwxrwx  1 root root 40 Nov 13  2020 pgsql-clusterdbman -> /usr/pgsql-12/share/man/man1/clusterdb.1
lrwxrwxrwx  1 root root 26 Nov 13  2020 pgsql-createdb -> /usr/pgsql-12/bin/createdb
lrwxrwxrwx  1 root root 39 Nov 13  2020 pgsql-createdbman -> /usr/pgsql-12/share/man/man1/createdb.1
lrwxrwxrwx  1 root root 28 Nov 13  2020 pgsql-createuser -> /usr/pgsql-12/bin/createuser
lrwxrwxrwx  1 root root 41 Nov 13  2020 pgsql-createuserman -> /usr/pgsql-12/share/man/man1/createuser.1
lrwxrwxrwx  1 root root 24 Nov 13  2020 pgsql-dropdb -> /usr/pgsql-12/bin/dropdb
lrwxrwxrwx  1 root root 37 Nov 13  2020 pgsql-dropdbman -> /usr/pgsql-12/share/man/man1/dropdb.1
lrwxrwxrwx  1 root root 26 Nov 13  2020 pgsql-dropuser -> /usr/pgsql-12/bin/dropuser
lrwxrwxrwx  1 root root 39 Nov 13  2020 pgsql-dropuserman -> /usr/pgsql-12/share/man/man1/dropuser.1
lrwxrwxrwx  1 root root 43 Nov 13  2020 pgsql-ld-conf -> /usr/pgsql-12/share/postgresql-12-libs.conf
lrwxrwxrwx  1 root root 31 Nov 13  2020 pgsql-pg_basebackup -> /usr/pgsql-12/bin/pg_basebackup
lrwxrwxrwx  1 root root 44 Nov 13  2020 pgsql-pg_basebackupman -> /usr/pgsql-12/share/man/man1/pg_basebackup.1
lrwxrwxrwx  1 root root 25 Nov 13  2020 pgsql-pg_dump -> /usr/pgsql-12/bin/pg_dump
lrwxrwxrwx  1 root root 28 Nov 13  2020 pgsql-pg_dumpall -> /usr/pgsql-12/bin/pg_dumpall
lrwxrwxrwx  1 root root 41 Nov 13  2020 pgsql-pg_dumpallman -> /usr/pgsql-12/share/man/man1/pg_dumpall.1
lrwxrwxrwx  1 root root 38 Nov 13  2020 pgsql-pg_dumpman -> /usr/pgsql-12/share/man/man1/pg_dump.1
lrwxrwxrwx  1 root root 28 Nov 13  2020 pgsql-pg_restore -> /usr/pgsql-12/bin/pg_restore
lrwxrwxrwx  1 root root 41 Nov 13  2020 pgsql-pg_restoreman -> /usr/pgsql-12/share/man/man1/pg_restore.1
lrwxrwxrwx  1 root root 22 Nov 13  2020 pgsql-psql -> /usr/pgsql-12/bin/psql
lrwxrwxrwx  1 root root 35 Nov 13  2020 pgsql-psqlman -> /usr/pgsql-12/share/man/man1/psql.1
lrwxrwxrwx  1 root root 27 Nov 13  2020 pgsql-reindexdb -> /usr/pgsql-12/bin/reindexdb
lrwxrwxrwx  1 root root 40 Nov 13  2020 pgsql-reindexdbman -> /usr/pgsql-12/share/man/man1/reindexdb.1
lrwxrwxrwx  1 root root 26 Nov 13  2020 pgsql-vacuumdb -> /usr/pgsql-12/bin/vacuumdb
lrwxrwxrwx  1 root root 39 Nov 13  2020 pgsql-vacuumdbman -> /usr/pgsql-12/share/man/man1/vacuumdb.1
lrwxrwxrwx  1 root root 16 Mar  9  2020 pip-3 -> /usr/bin/pip-3.6
lrwxrwxrwx  1 root root 15 Mar  9  2020 pip3 -> /usr/bin/pip3.6
lrwxrwxrwx  1 root root 17 Mar  9  2020 pydoc-3 -> /usr/bin/pydoc3.6
lrwxrwxrwx  1 root root 17 Mar  9  2020 pydoc3 -> /usr/bin/pydoc3.6
lrwxrwxrwx  1 root root 22 Jun 16  2020 python -> /usr/libexec/no-python
lrwxrwxrwx  1 root root 18 Mar  9  2020 python3 -> /usr/bin/python3.6
lrwxrwxrwx  1 root root 34 Mar  9  2020 python3-man -> /usr/share/man/man1/python3.6.1.gz
lrwxrwxrwx  1 root root 19 Mar  9  2020 pyvenv-3 -> /usr/bin/pyvenv-3.6
lrwxrwxrwx  1 root root 64 May  2 17:58 rmic -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/rmic
lrwxrwxrwx  1 root root 72 May  2 17:58 rmic.1.gz -> /usr/share/man/man1/rmic-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 64 May  2 17:58 rmid -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/rmid
lrwxrwxrwx  1 root root 72 May  2 17:58 rmid.1.gz -> /usr/share/man/man1/rmid-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 71 May  2 17:58 rmiregistry -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/rmiregistry
lrwxrwxrwx  1 root root 79 May  2 17:58 rmiregistry.1.gz -> /usr/share/man/man1/rmiregistry-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 69 May  2 17:58 serialver -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/serialver
lrwxrwxrwx  1 root root 77 May  2 17:58 serialver.1.gz -> /usr/share/man/man1/serialver-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 69 May  2 17:58 unpack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/unpack200
lrwxrwxrwx  1 root root 77 May  2 17:58 unpack200.1.gz -> /usr/share/man/man1/unpack200-java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64.1.gz
lrwxrwxrwx  1 root root 43 Jun 16  2020 unversioned-python-man -> /usr/share/man/man1/unversioned-python.1.gz
lrwxrwxrwx  1 root root 17 Jun 24  2020 whois -> /usr/bin/whois.md
lrwxrwxrwx  1 root root 33 Jun 24  2020 whois-man -> /usr/share/man/man1/whois.md.1.gz


update-alternatives --list
libnssckbi.so.x86_64    auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                  auto    /usr/libexec/no-python
cifs-idmap-plugin       auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
ifup                    auto    /usr/libexec/nm-ifup
python3                 auto    /usr/bin/python3.6
ld                      auto    /usr/bin/ld.bfd
java                    manual  /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/java
jre_openjdk             auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64/jre
jre_1.8.0               auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64/jre
jre_1.8.0_openjdk       auto    /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
jre_11                  auto    /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
jre_11_openjdk          auto    /usr/lib/jvm/jre-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
javac                   auto    /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64/bin/javac
java_sdk_openjdk        auto    /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
java_sdk_11             auto    /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64
java_sdk_11_openjdk     auto    /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.el8_3.x86_64

**Comment by bdpz** [comment]
I try to find a solution...

Maybe the simpliest way is to save and restore the content of **/etc/alternatives** AND **/var/lib/alternatives** ?

It works for me, but that's not transparent because you have to execute again **update-alternatives --config java** in order to relink /usr/bin/java (and the others java bin) with /etc/alternatives

[root@sourceforge ~]# ll /usr/bin/ | grep altern | grep java
lrwxrwxrwx  1 root root          26 Nov  2  2020 alt-java -> /etc/alternatives/alt-java
lrwxrwxrwx  1 root root          22 Nov  2  2020 java -> /etc/alternatives/java
lrwxrwxrwx  1 root root          23 Nov  2  2020 javac -> /etc/alternatives/javac
lrwxrwxrwx  1 root root          25 Nov  2  2020 javadoc -> /etc/alternatives/javadoc
lrwxrwxrwx  1 root root          23 Nov  2  2020 javap -> /etc/alternatives/javap

**Comment by andrewlukoshko** [comment]
The script was updated to keep all alternatives symlinks during migration.
Please check it for your cases.
Thanks.

**Comment by bdpz** [comment]
After some more checks, some links are broken in /usr/bin

pack200 -> /etc/alternatives/pack200
python -> /etc/alternatives/unversioned-python
rmid -> /etc/alternatives/rmid
tnameserv -> /etc/alternatives/tnameserv
unpack200 -> /etc/alternatives/unpack200

Here is the state of those links before upgrade :

ll /etc/alternatives/pack200 
lrwxrwxrwx 1 root root 67 Jun  7 09:23 /etc/alternatives/pack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/pack200

ll /etc/alternatives/unversioned-python
ls: cannot access '/etc/alternatives/unversioned-python': No such file or directory

ll /etc/alternatives/rmid
lrwxrwxrwx 1 root root 64 Jun  7 09:23 /etc/alternatives/rmid -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/rmid

ll /etc/alternatives/tnameserv
ls: cannot access '/etc/alternatives/tnameserv': No such file or directory

ll /etc/alternatives/unpack200
lrwxrwxrwx 1 root root 69 Jun  7 09:23 /etc/alternatives/unpack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/unpack200

So /etc/alternatives/unversioned-python and /etc/alternatives/tnameserv were added by Alma, and /etc/alternatives/pack200, /etc/alternatives/rmid and /etc/alternatives/unpack200 are missing.

**Comment by andrewlukoshko** [comment]
Thank you for update!
We'll fix that soon

**Comment by soksanichenko** [comment]
@bdpz Hello.
Could please write the reproducing steps of the last issue?
Because I installed CentOS 8, the same version of openjdk, converted the system and got only one broken link.
It's `/usr/bin/python -> /etc/alternatives/unversioned-python`
Or maybe I misunderstood you.
```[root@localhost ~]# ll /usr/bin/python
lrwxrwxrwx. 1 root root 36 Jun 14 08:14 /usr/bin/python -> /etc/alternatives/unversioned-python
[root@localhost ~]# ll /usr/bin/tnameserv
ls: cannot access '/usr/bin/tnameserv': No such file or directory
[root@localhost ~]# ll /usr/bin/rmid
lrwxrwxrwx. 1 root root 22 Jun 14 08:14 /usr/bin/rmid -> /etc/alternatives/rmid
[root@localhost ~]# ll /usr/bin/pack200
lrwxrwxrwx. 1 root root 25 Jun 14 08:14 /usr/bin/pack200 -> /etc/alternatives/pack200
[root@localhost ~]# ll /usr/bin/unpack200
lrwxrwxrwx. 1 root root 27 Jun 14 08:14 /usr/bin/unpack200 -> /etc/alternatives/unpack200
[root@localhost ~]# ll /etc/alternatives/rmid
lrwxrwxrwx. 1 root root 64 Jun 14 08:14 /etc/alternatives/rmid -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/rmid
[root@localhost ~]# ll /etc/alternatives/pack200
lrwxrwxrwx. 1 root root 67 Jun 14 08:14 /etc/alternatives/pack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/pack200
[root@localhost ~]# ll /etc/alternatives/unpack200
lrwxrwxrwx. 1 root root 69 Jun 14 08:14 /etc/alternatives/unpack200 -> /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/bin/unpack200
[root@localhost ~]# ll /etc/alternatives/tnameserv
ls: cannot access '/etc/alternatives/tnameserv': No such file or directory
[root@localhost ~]# ll /etc/alternatives/unversioned-python
ls: cannot access '/etc/alternatives/unversioned-python': No such file or directory
[root@localhost ~]#
```
Thank you!

**Comment by bdpz** [comment]
My system : 

more /etc/redhat-release 
CentOS Linux release 8.4.2105

This system was first installed with Centos 8.0, and then upgraded in 8.1, 8.2, 8.3 and 8.4. I don't have any broken links.

Installed java RPM :

rpm -qa | grep java
java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64
java-11-openjdk-devel-11.0.11.0.9-2.el8_4.x86_64
tzdata-java-2021a-1.el8.noarch
javapackages-filesystem-5.3.0-1.module_el8.0.0+11+5b8c10bd.noarch
java-11-openjdk-headless-11.0.11.0.9-2.el8_4.x86_64
java-1.8.0-openjdk-headless-1.8.0.292.b10-1.el8_4.x86_64

I have selected java11 with update-alternatives --config java

Installation of Alma :
poweroff
snapshot of the VM (VMWare)
poweron
dnf update
cd
curl -O https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/master/almalinux-deploy.sh
bash almalinux-deploy.sh (as root)

And finally "reboot" (after all is "green")

That's all !

I have seen that /etc/alternatives symlinks disappears at the end of the script, during the "scriptlet" phase.

I have restored my snapshot to compare the two systems (Centos and Alma).

**Comment by soksanichenko** [comment]
Thank you very much.
I just installed only one openjdk. I will try to install both and find an issue in the script.

**Comment by soksanichenko** [comment]
@bdpz Hello.
Could you please try this variant of script?
https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/issue_50/almalinux-deploy.sh
And please send me the following items if this variant won't help to you.
1. Log file `/var/log/almalinux-deploy.debug.log`
2. Directory `/tmp/alternatives_backup/`

Thank you!

**Comment by bdpz** [comment]
This variant helped me, all is ok in /etc/alternatives and /usr/bin, thanks all lot !

The system rebooted like a charm ;)

I have attached the logs if you want to check the result of the deploy script.

[almalinux-deploy.debug.log.gz](https://github.com/AlmaLinux/almalinux-deploy/files/6654413/almalinux-deploy.debug.log.gz)

**Comment by soksanichenko** [comment]
I'm very happy to hear it. 
Thanks for update and logs.
